---
format: 
  revealjs:
    slide-number: true
    code-link: true
    highlight-style: a11y
    chalkboard: true
    theme:
      - nceas_styles.scss
---

## {#title-slide data-menu-title="Title Slide"} 

[Just enough CSS (and Sass)]{.custom-title}

[for data scientists looking to add a little *pizzazz* to their webpages]{.custom-subtitle}

<hr class="hr-red">

<br>

:::: {.columns} 

::: {.column width="50%"}
[**Sam Csik** |]{.custom-subtitle2}<br>
[Data Training Coordinator]{.custom-subtitle2}<br>
[*National Center for Ecological Analysis & Synthesis*]{.custom-subtitle3}
:::

::: {.column width="50%"}
[**Roundtable** |]{.custom-subtitle2}<br>
[August 2023]{.custom-subtitle2}<br>
[*National Center for Ecological Analysis & Synthesis*]{.custom-subtitle3}
:::

::::

<br>

::: {.center-text .caption-text}
Slides & source code available on [{{< fa brands github title = "GitHub icon" >}}](https://github.com/samanthacsik/just-enough-css-sass)
:::

---

##  {#follow-along data-menu-title="Setup"}

[Setup]{.slide-title}

<hr>

::: {.large-body-text .center-text}
**There will be some hands-on activities sprinkled throughout this talk!**
:::

::: {.body-text .center-text}
<!-- If you'd like to follow along, please take a moment to grab the materials from the associated GitHub repository, <https://github.com/samanthacsik/cute-cats-dogs>, by either forking/cloning or downloading the repo. You can find **instructions for both options, below.** -->
*If you'd like to follow along, please be sure to:*
:::

::: {.body-text}
1. **install [R](https://cloud.r-project.org/) and [RStudio](https://posit.co/products/open-source/rstudio/)** -- I'll be using RStudio, though you may use alternative IDEs (e.g. VS Code) if that's where you're most comfortable
2. **install [Quarto](https://quarto.org/docs/get-started/)** -- this may require updating R/RStudio if you already have those installed
3. **grab the materials from GitHub**, <https://github.com/samanthacsik/cute-cats-dogs>, using one of the following approaches:
    a. [instructions for downloading the GitHub repository to work locally](https://github.com/samanthacsik/cute-cats-dogs/wiki/Download-the-GitHub-repository-to-work-locally) (do this if you **don't** have git/GitHub configured)
    b. [instructions for forking & cloning the GitHub respository](https://github.com/samanthacsik/cute-cats-dogs/wiki/Forking-&-Cloning-a-GitHub-respository) (do this if you **do** have git/GitHub configured)
:::

<!-- ::: {.body-text} -->
<!-- -  If you **don't** have git/GitHub configured: [Instructions for downloading the GitHub repository to work locally](https://github.com/samanthacsik/cute-cats-dogs/wiki/Download-the-GitHub-repository-to-work-locally) -->
<!-- - If you **do** have git/GitHub configured: [Instructions for forking & cloning the GitHub respository](https://github.com/samanthacsik/cute-cats-dogs/wiki/Forking-&-Cloning-a-GitHub-respository) -->
<!-- ::: -->

---

{{< include sections/1-intro.qmd >}}

---

{{< include sections/2-html-css-intro.qmd >}}

---

{{< include sections/3-html.qmd >}}

---

{{< include sections/4-write-html.qmd >}}

